# Generated by Django 3.0.3 on 2020-09-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('cores', models.CharField(max_length=100)),
                ('use_rate', models.CharField(max_length=300)),
            ],
        ),
    ]
