# Generated by Django 3.0.3 on 2020-09-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataShow', '0002_system_monit_cpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_monitor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpu_cores', models.IntegerField()),
                ('cur_cpu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mem_use', models.IntegerField()),
                ('mem_all', models.IntegerField()),
                ('cur_mem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_time', models.DateTimeField()),
                ('time_stamp', models.BigIntegerField()),
            ],
        ),
    ]
