# Generated by Django 3.0.3 on 2020-09-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataShow', '0003_system_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_monitor',
            name='cur_gpu',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_monitor',
            name='gpu_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_monitor',
            name='gpu_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_monitor',
            name='gpudriver_info',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_monitor',
            name='gpumem_all',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_monitor',
            name='gpumem_free',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_monitor',
            name='gpumem_use',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
